"""empty message

Revision ID: 1da25c20ece7
Revises: 06f534a8e6f8
Create Date: 2023-04-19 14:00:59.301737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da25c20ece7'
down_revision = '06f534a8e6f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('other')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
