"""empty message

Revision ID: 742414c9c6eb
Revises: 1da25c20ece7
Create Date: 2023-04-19 14:03:07.203731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742414c9c6eb'
down_revision = '1da25c20ece7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
